create table public.fantasypros_rankings (
  id bigint generated by default as identity primary key,
  season integer not null,
  format text not null default 'redraft',
  scoring text not null default 'PPR',
  position text not null default 'all',
  player_name text not null,
  rank_ecr integer,
  rank_adp numeric,
  payload jsonb not null,
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (season, format, scoring, position, player_name)
);

create index fantasypros_rankings_lookup_idx
  on public.fantasypros_rankings (season, format, scoring, position, rank_ecr);

alter table public.fantasypros_rankings enable row level security;

create policy "Authenticated users can read rankings"
  on public.fantasypros_rankings
  for select
  to authenticated
  using (true);

revoke all on public.fantasypros_rankings from anon;
grant select on public.fantasypros_rankings to authenticated;
